### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/foundation#21] opened 2018-08-09 11:54 UTC
## Problem statement:
At this moment it's not clear what we are going to do with the website (foundation.forus.io)

1. Instead of using Django, we should use gh-pages (just like docs.forus.io)
2. There are some minor issue and improvements need to be done on the current website, but it's unclear if the investment in time and resources is worth it.
3. Before we drop Django as CMS, we should decide if its necessary to do a re-design.

## Proposed solution:
1. Drop Django as CMS and start building the website on GitHub pages.
    a. Keep the current design as it is (for now)
    b. Redesign the entire website.

Before we invest more time in the current website we should make a decision.
I'm able to create the website in Github pages, but I should invest my time in testing because we are almost at the deadline of the following release.

**Comment by jamalv** [comment] 2018-08-09 12:34
I personally think the focus now should be on the knowledge base (content of the website) and brand identity that we will continue on and after the app designs are finished. Until then working on the current website is a bit like “mopping with an open tap” (dutch expression).

**Comment by jknnr** [comment] 2018-08-09 12:40
@GerbenBosschieter Сan you give more context about why we should start using GH-pages for the whole web-site? What is the exact problem with using the current CMS?
There are cases that can not be easily implemented on wiki-frontends. Contact form for example. 
If we are gonna use Docker, it will be even more complicated.
So just convey your idea, and then we will follow and discuss.
*Btw the favicon issue has nothing to do with Django.

**Comment by danrminds** [comment] 2018-08-09 12:52
I will agree here with Yasha, not sure if necessary to implement the whole website with gh-pages.
Regarding design - I think we should do a rebranding to allign it with the front-ends and designs of the landing pages for dashboards and MeApp

**Comment by GerbenBosschieter** [comment] 2018-08-09 12:55
@yasha , no the issue itself had nothing to do with Django. But Django was my issue xD

Well I've never said there was an issue with the current CMS. There was an issue created to research the possibilities(https://github.com/teamforus/foundation/issues/12), so I did. The CMS itself is not a problem. But if you wanna change other things in the website it would be easier to use gh-pages, we already used gh-ages for docs.forus.io. 
gh-pages gets rendered by Jekyll and thing like contact forms are possible.

look at the website of rocket.chat. The complete website is build with gh-pages and Jekyll
https://rocket.chat

Why Rocket.Chat uses gh-pages:

Site structure

We chose Jekyll and GitHub pages because together they offer the most supported and user friendly way for others to fork, edit, preview and contribute documentation without having to setup a local development environment just to write copy, add images or manage files.

For developers, only use templates and includes when they are needed. Creating a template per page or splitting templates into many parts that are only included once makes it challenging to maintain and contribute to the project.

**Comment by GerbenBosschieter** [comment] 2018-08-09 12:58
@danrminds Oke, I understand. But sometimes there are some issues that need to be solved with the website and people assign me to it. But I don't know much about Django, I can do stuff with it if I do trial and error. But thats something I want to do locally and could't get it working locally, not even with help. It took to much time.

If you guys want to leave it this way, that's okay. But in that case I am not able to solve all the issues of the website.

**Comment by danrminds** [comment] 2018-08-09 13:01
I will research the option with gh-pages and Jekyll, and see how far we can get with it.

**Comment by maxvisser** [comment] 2018-08-09 13:04
my main issue with the current website is not design or django but just that the content is really outdated. I also think there is no redesign needed, probably only the CSS need some change to align colors and logo to the landing pages of the platform.

**Comment by GerbenBosschieter** [comment] 2018-08-09 13:10
@dan we've already researched it. https:/docs.forus.io  is currently working with gh-pages and Jekyll. So it's doable and thats also something I am more capable to do than Django. But if it's worth the time right now? I dunno. 

@maxvisser @jamalv I agree, content is most important for the short term. But in that case I can't solve the issues created for the website and someone else should do it. So I can focus on Support an Testing

**Comment by jamalv** [comment] 2018-08-09 13:36
Yea, I really like the idea of content managment trough github. It will be much more collaborative than using a standard CMS and having to give out passwords. This way anyone can update the content trough a pull-request and the standard way of reviewing can be applied.

**Comment by GerbenBosschieter** [comment] 2018-08-09 13:37
@dan credits to max, i allready creatief a docs page. But @maxvisser killes my baby and creaties thia ons :D

**Comment by TomForus** [comment] 2018-08-10 07:55
I agree with Max regarding the content on the website.

 Personally I think the website should be informative and have a clean and attracting look. The content must be informative enough to give the municipalities or other potential customers a clear view about the product we are developing.

**Comment by maartenfv** [comment] 2018-08-10 08:04
I like making it easier to edit the texts on the website. The lower the barrier, the easier improve to the content. At this moment even small improvements are a hassle.

Docs.forus.io is great. Using github as a cms seems most suitable and it is in line with allowing everyone to contribute and improve.

**For the website let´s have a vote on the Github CMS for the rest of the website**

After this we have basic consensus and we can then fill in the details.

Give this comment a thumbs up if you like it and a thumbs down if you do not. @jamalv @TomForus @maxvisser @GerbenBosschieter @jknnr @linda-90 

By the end of the day we can look at the result. If postive we continue with making a planning to execute this project. If negative we continue with the discussion until we are ready for another vote.

**Comment by danrminds** [comment] 2018-08-10 08:33
I got convinced about switching to gh-pages as a CMS. If this will make it easier for future to update the content -  of course let's do it. 

My next question will be how far we go with alignment of the old design with the new landing pages / dashboard and app. 
Also we have to think about where and how we integrate those landing pages in the structure of the website, maybe we would need a new "products" page

**Comment by jknnr** [comment] 2018-08-10 10:44
In my opinion for the nearest future we should proceed using django for everything that is not knowledge base. 
Why?
1. Conceptually our landing page was meant to be more like our business card, for municipalities and clients. Not the developer's wiki-style thing. Now we have a very sweet part (docs), and let it be gh, it really makes sense here. But giving community the ability to make proposals about the text (about our company and product) from a landing page makes no sense to me. Internally – yes, but again we can open an issue on github and then someone will just change the content by logging in to Django – it literally takes 1 minute. What @TomForus is saying in his message does not involve any migration.
2. All the arguments I've seen so far were vague like "The CMS itself is not a problem. But if you wanna change **other things** in the website it would be easier to use gh-pages". Or "At this moment even **small improvements are a hassle**".  [Again, favicon is nothing to deal with the CMS].
Text edits, images, content blocks are working just fine. If not, explain please.
3. Without any doubt django and other solutions have its pros and cons, but I'm sure there will be also with gh-pages. I've given you examples earlier in this thread, no one has still answered.
So if the problem is content, let's discuss and change it. @GerbenBosschieter If there are issues and hassles with Django let me know about it, and maybe we will figure them out.
IMHO spending effort to change what is still working is not the priority for the team right now. 
I am looking forward to discussing it more. But for now my vote is against changing the WHOLE thing to GH.

**Comment by maxvisser** [comment] 2018-08-10 15:06
Building the current site on gh-pages would be a day of work for me.

I see multiple pros for moving to gh-pages but the cons are also there as yasha said.
One pro i havent heard in this issue yet is that github pages is free. There are no hosting costs or server maintance costs, deployment is automatically.

**Comment by maxvisser** [comment] 2018-08-10 16:32
Mvp of the site in gh-pages. So basically copying all existing features over. Contact form and multiple languages are the uncertain parts i think who could take longer than a day to port to ghpages.

I voted against migration btw because i think we should just start with new content first.

**Comment by danrminds** [comment] 2018-08-10 16:34
@maxvisser From what we discussed today - even if we will go with the migration - it will be in September. First indeed has to go the content writing. So voting does not go for migration at this very moment.

**Comment by maxvisser** [comment] 2018-08-14 09:00
I looked at the contact form of <https://rocket.chat> it still uses a rest api backend for sending mails. I can't find this backend on their github page. It is hosted at <http://rocket-chat.appspot.com>

**Comment by maartenfv** [comment] 2018-08-14 11:03
@maxvisser  You are right about the content, we should fix it first before moving to the next steps. We are working on this and the progress so far can be found at: 

https://drive.google.com/drive/folders/1ig9PHLiEjhvrwD7JZQyQ3qqHs_iOdFFQ

We will place this content in the knowledge base as well.

I will give an update when ready.

Listening to all the arguments and seeing the vote I suggest the following:

**Step 1 Quick fixes until 1 September** 

We will improve the texts on the website using Django.

**Step 2 New website 1 September until 1 Oktober**

We start with a clear project plan and budget.
Move from content to wire-framing, to design, to coding, etc.

This will result in having a website with better content, a new designs in line with our new style and a connection to GitHub.

**Comment by maartenfv** [comment] 2018-09-13 13:32
@GerbenBosschieter What is the status?

**Comment by GerbenBosschieter** [comment] 2018-09-14 09:56
@maartenfv We did the planning, next meeting about the website is Monday. We are currently focussing on november 1th for implementation. There is a lot to do there. Al those different projects on the same time is hard to manage. So we will be working on it, but I will not let it interfere with things that have an higher priority.

**Comment by jamalv** [comment] 2018-09-17 09:37
Had a discussion with @maartenfv and @TomForus and we came to the same conclusion. Implementation ZH is main prio until november. We can work on the site on the side :) (content trough knowledge base and brand identity styleguides) After nov it will become more important.

**Comment by maartenfv** [comment] 2018-12-13 08:57
Will close this for now. General webshop will be the new website on forus.io. The old website will still be online on about.forus.io. In future we look at adding Github as a CMS.

**Closed by maartenfv** 2018-12-13 08:57 UTC
